#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# Where this repo is, derived from the script's own location, so the wizard can
# be run from any directory.
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)
BOOTSTRAP="$REPO_ROOT/app/bootstrap"
PROJECT_DIR="$REPO_ROOT/app/Hoppa"
PBXPROJ="$PROJECT_DIR/Hoppa.xcodeproj/project.pbxproj"
APP_SRC_DIR="$PROJECT_DIR/Hoppa"

# The captured facts land here, not in a .env — they are the answer to ticket
# 0018 and get folded into its resolution.
ENV_FILE="$BOOTSTRAP/ticket-0018-facts.env"

BUNDLE_ID="com.robvb.hoppa"
MIN_IOS="17.0"

banner "Hoppa — an empty app on the phone (ticket 0018)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "The Mac and the tools"
say "Nothing to decide here. The wizard reads what you already have."
printf '\n'

if [[ "$(uname -s)" != "Darwin" ]]; then
  warn "This is not macOS. Run this wizard on the Mac, inside the fitty repo."
  exit 1
fi

XCODE_VERSION=$(xcodebuild -version 2>/dev/null | head -1 | awk '{print $2}' || true)
if [[ -z "$XCODE_VERSION" ]]; then
  warn "xcodebuild did not answer. Xcode is missing, or only the Command Line Tools are installed."
  step "Install Xcode from the Mac App Store, then open it once and accept the licence."
  note "If it is installed already, run:  sudo xcode-select -s /Applications/Xcode.app  and  sudo xcodebuild -license accept"
  open_url "https://apps.apple.com/app/xcode/id497799835"
  pause "Press Enter when Xcode opens and the licence is accepted."
  XCODE_VERSION=$(xcodebuild -version 2>/dev/null | head -1 | awk '{print $2}' || true)
  [[ -n "$XCODE_VERSION" ]] || { warn "Still no xcodebuild. Fix that first, then re-run this wizard."; exit 1; }
fi

XCODE_MAJOR=${XCODE_VERSION%%.*}
SWIFT_VERSION=$(xcrun swift -version 2>&1 | head -1 | sed -E 's/.*version ([0-9.]+).*/\1/' || true)
MACOS_VERSION=$(sw_vers -productVersion || true)

say "macOS      $MACOS_VERSION"
say "Xcode      $XCODE_VERSION"
say "Swift      ${SWIFT_VERSION:-unknown}"
printf '\n'
write_env MACOS_VERSION "$MACOS_VERSION"
write_env XCODE_VERSION "$XCODE_VERSION"
write_env SWIFT_VERSION "${SWIFT_VERSION:-unknown}"
pause "Press Enter to continue."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Apple Developer Program, and Xcode's account"
say "You chose the paid route: a signed build lasts a year, not seven days."
say "A free Apple ID also works today, and the app then stops launching after 7 days."
printf '\n'
step "Enrol as an individual. Apple can take up to 48 hours to approve."
open_url "https://developer.apple.com/programs/enroll/"
printf '\n'
step "Then in Xcode: menu Xcode > Settings > Accounts > + > Apple Account, and sign in."
note "The account must appear there, or the Team dropdown in stage 6 stays empty."
printf '\n'

if confirm "Is your paid Apple Developer membership active?"; then
  SIGNING_ROUTE="Apple Developer Program (paid)"
  SIGNING_TERM="1 year"
else
  SIGNING_ROUTE="free Apple ID (enrolment pending)"
  SIGNING_TERM="7 days"
  warn "Continuing on a free Apple ID. The build will stop launching after 7 days."
  note "Re-run this wizard after Apple approves you, and press Run in Xcode again."
fi
write_env SIGNING_ROUTE "$SIGNING_ROUTE"
write_env SIGNING_TERM "$SIGNING_TERM"
pause "Press Enter to continue."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Create the Xcode project"
say "Open Xcode and choose File > New > Project. Use exactly these values:"
printf '\n'
step "Template:        iOS  >  App"
step "Product Name:    Hoppa"
step "Team:            your Apple Developer team (or your personal team)"
step "Organization Identifier:  com.robvb"
note "Xcode pre-fills this with your name. Clear it and type com.robvb."
note "If you leave it, stage 4 corrects it anyway."
step "Interface:       SwiftUI"
step "Language:        Swift"
step "Testing System:  Swift Testing with XCTest UI Tests"
step "Storage:         None"
step "Host in CloudKit: OFF"
printf '\n'
note "Xcode 15 shows an 'Include Tests' tick box instead of Testing System. Tick it."
printf '\n'
step "Save it into:    $REPO_ROOT/app"
warn "UNCHECK 'Create Git repository' — this repo already has one."
printf '\n'
note "That gives app/Hoppa/Hoppa.xcodeproj. The next stage corrects the bundle id,"
note "the iOS version and the orientation, so do not hand-edit those now."
printf '\n'

while [[ ! -f "$PBXPROJ" ]]; do
  pause "Press Enter when the project is created."
  if [[ ! -f "$PBXPROJ" ]]; then
    warn "Not found: app/Hoppa/Hoppa.xcodeproj"
    note "Expected at: $PBXPROJ"
    confirm "Try again?" || { warn "Stopping. Re-run the wizard when the project exists."; exit 1; }
  fi
done
say "Found the project."
pause "Press Enter to continue."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Correct the project settings"
say "The wizard edits project.pbxproj directly, so there is nothing to click."
printf '\n'
say "bundle id     $BUNDLE_ID   (whatever prefix Xcode chose is replaced)"
say "min iOS       $MIN_IOS"
say "orientation   portrait only"
say "devices       iPhone only"
printf '\n'

cp "$PBXPROJ" "$PBXPROJ.before-wizard"
sed -i.tmp \
  -e "s/PRODUCT_BUNDLE_IDENTIFIER = \"[A-Za-z0-9.-]*\.Hoppa\([A-Za-z]*\)\";/PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID\1;/g" \
  -e "s/PRODUCT_BUNDLE_IDENTIFIER = [A-Za-z0-9.-]*\.Hoppa\([A-Za-z]*\);/PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID\1;/g" \
  -e "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = $MIN_IOS;/g" \
  -e 's/INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone = "[^"]*";/INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone = UIInterfaceOrientationPortrait;/g' \
  -e 's/TARGETED_DEVICE_FAMILY = "[^"]*";/TARGETED_DEVICE_FAMILY = "1";/g' \
  "$PBXPROJ"
rm -f "$PBXPROJ.tmp"

printf '\n'
if grep -q "PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID;" "$PBXPROJ"; then
  say "bundle id    ✓ $BUNDLE_ID"
else
  warn "The bundle id did not change. Set it by hand:"
  note "  target Hoppa > Signing & Capabilities > Bundle Identifier = $BUNDLE_ID"
  SKIPPED+=("bundle identifier — set it by hand to $BUNDLE_ID")
fi
grep -q "IPHONEOS_DEPLOYMENT_TARGET = $MIN_IOS;" "$PBXPROJ" \
  && say "min iOS      ✓ $MIN_IOS" \
  || { warn "Minimum iOS unchanged — set it in target Hoppa > General > Minimum Deployments."; SKIPPED+=("minimum iOS — set it by hand to $MIN_IOS"); }
grep -q "INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone = UIInterfaceOrientationPortrait;" "$PBXPROJ" \
  && say "orientation  ✓ portrait only" \
  || { warn "Orientation unchanged — untick both Landscape boxes in target Hoppa > General."; SKIPPED+=("orientation — untick Landscape Left and Landscape Right"); }

printf '\n'
note "The untouched original is kept at project.pbxproj.before-wizard"

# Record what is actually in the file, never what we meant to put there. An
# earlier version wrote the intended values here regardless of whether the
# patch took, and the facts file asserted a bundle id the project never had.
ACTUAL_BUNDLE=$(grep -o 'PRODUCT_BUNDLE_IDENTIFIER = [^;]*;' "$PBXPROJ" \
  | sed 's/.*= //; s/;$//' | grep -vi 'tests' | head -1)
ACTUAL_MIN=$(grep -o 'IPHONEOS_DEPLOYMENT_TARGET = [^;]*;' "$PBXPROJ" \
  | sed 's/.*= //; s/;$//' | head -1)
if grep -q 'INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone = UIInterfaceOrientationPortrait;' "$PBXPROJ"; then
  ACTUAL_ORIENT="portrait only, iPhone only"
else
  ACTUAL_ORIENT="NOT portrait-only — check the project"
fi
write_env BUNDLE_ID "${ACTUAL_BUNDLE:-unknown}"
write_env MIN_IOS "${ACTUAL_MIN:-unknown}"
write_env ORIENTATION "$ACTUAL_ORIENT"
pause "Press Enter to continue."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Install the smoke test"
say "Two Swift files and three font files. They replace what the template made."
printf '\n'

[[ -d "$APP_SRC_DIR" ]] || { warn "No source folder at $APP_SRC_DIR"; exit 1; }

ENTRY_FILE="$APP_SRC_DIR/HoppaApp.swift"
if [[ ! -f "$ENTRY_FILE" ]]; then
  ENTRY_FILE=$(find "$APP_SRC_DIR" -maxdepth 1 -name '*App.swift' | head -1 || true)
  [[ -n "$ENTRY_FILE" ]] || { warn "Cannot find the app entry file in $APP_SRC_DIR"; exit 1; }
  note "Using $(basename "$ENTRY_FILE") as the entry file."
fi

cp "$BOOTSTRAP/Sources/HoppaApp.swift" "$ENTRY_FILE"
cp "$BOOTSTRAP/Sources/ContentView.swift" "$APP_SRC_DIR/ContentView.swift"
mkdir -p "$APP_SRC_DIR/Fonts"
cp "$BOOTSTRAP/Fonts/"* "$APP_SRC_DIR/Fonts/"
say "copied  $(basename "$ENTRY_FILE"), ContentView.swift, Fonts/ (Anton + IBM Plex Sans + their licences)"
printf '\n'

if (( XCODE_MAJOR >= 16 )); then
  note "Xcode $XCODE_MAJOR syncs the project folder, so the new files appear by themselves."
else
  warn "Xcode $XCODE_MAJOR does not sync folders. Add the fonts by hand:"
  step "Drag the Fonts folder from Finder into the Hoppa group in Xcode."
  step "Tick 'Copy items if needed' and tick the Hoppa target."
  pause "Press Enter when the Fonts folder shows in the project navigator."
fi
printf '\n'
note "The fonts register at runtime, so there is no Info.plist to edit."
pause "Press Enter to continue."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Signing"
say "In Xcode, click the blue Hoppa project, then the Hoppa target."
printf '\n'
step "Open the Signing & Capabilities tab."
step "Tick 'Automatically manage signing'."
step "Choose your Team in the dropdown."
step "Check that Bundle Identifier reads $BUNDLE_ID"
printf '\n'
note "A red 'failed to register bundle identifier' means the id is taken. Tell me and we pick another."
printf '\n'
ask TEAM_NAME "Which Team did you choose? (the name as Xcode shows it)"
write_env TEAM_NAME "$TEAM_NAME"
pause "Press Enter to continue."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Run it on the phone"
say "The simulator does not count. This must run on the real iPhone."
printf '\n'
step "Connect the iPhone by cable. Unlock it and tap Trust."
step "On the phone: Settings > Privacy & Security > Developer Mode > on, then restart the phone."
step "In Xcode, pick your iPhone in the run destination at the top."
step "Press Run (Cmd-R)."
printf '\n'
if [[ "$SIGNING_TERM" == "7 days" ]]; then
  step "First launch on a free account fails once. On the phone:"
  note "  Settings > General > VPN & Device Management > your Apple ID > Trust. Then run again."
  printf '\n'
fi
say "You should see: a near-black screen, 72.5 KG in a heavy condensed face,"
say "and three rows that each say LOADED in green."
printf '\n'
warn "If any row says FALLBACK in red, that face did not register. Note which one."
printf '\n'
pause "Press Enter when the app is on the phone (or when it refuses to be)."

DEVICES=$(xcrun devicectl list devices 2>/dev/null | grep -iv "^Devices\|^$" | head -5 || true)
if [[ -n "$DEVICES" ]]; then
  say "Xcode sees:"
  printf '%s\n' "$DEVICES" | while IFS= read -r line; do note "  $line"; done
  printf '\n'
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Record what happened"
say "These answers become the resolution of ticket 0018."
printf '\n'
ask PHONE_MODEL "iPhone model:"
ask PHONE_IOS "iOS version on it:"
ask FONTS_OK "Did all three rows say LOADED? (yes / which one failed)"
ask FOUGHT_BACK "Anything that fought back? (one line, or 'nothing')"
write_env PHONE_MODEL "$PHONE_MODEL"
write_env PHONE_IOS "$PHONE_IOS"
write_env FONTS_OK "$FONTS_OK"
write_env FOUGHT_BACK "$FOUGHT_BACK"

PROFILE_DIR="$HOME/Library/Developer/Xcode/UserData/Provisioning Profiles"
EXPIRY=""
NEWEST=$(ls -t "$PROFILE_DIR"/*.mobileprovision 2>/dev/null | head -1 || true)
if [[ -n "$NEWEST" ]]; then
  EXPIRY=$(security cms -D -i "$NEWEST" 2>/dev/null | plutil -extract ExpirationDate raw -o - - 2>/dev/null || true)
fi
if [[ -n "$EXPIRY" ]]; then
  printf '\n'
  say "Signing expires: $EXPIRY"
else
  printf '\n'
  note "Could not read the provisioning profile date."
  ask SIGNING_EXPIRY "When does the build expire? (a date, or 'unknown')"
  EXPIRY="$SIGNING_EXPIRY"
fi
write_env SIGNING_EXPIRY "$EXPIRY"

finish
note "Now tell me the wizard is done. I read $ENV_FILE and close ticket 0018."
printf '\n'
