extension Phrasebook {
    func dutch(_ phrase: Phrase) -> String {
        switch phrase {
        case .tabHome: "Home"
        case .tabHistory: "Geschiedenis"
        case .tabProgress: "Voortgang"
        case .tabSettings: "Instellingen"
        case .language: "Taal"
        case .selected: "Gekozen"
        case .nothingHereYet: "Nog niets hier"
        case .createAProgram: "Maak een programma"
        case .pickADay: "Kies een dag"
        case .running: "Bezig"
        case .hoppaCannotReadLogbook: "Hoppa kan je logboek niet lezen."
        case .fileUnchanged: "Er is niets veranderd. Het bestand is precies zoals het was."
        case .resume: "Ga verder"
        case .finishIt: "Afronden"
        case .discardIt: "Weggooien"
        case .discardThisWorkout: "Deze workout weggooien?"
        case .everyLoggedSetGoes: "Elke gelogde set gaat mee. Hoppa bewaart niets."
        case .keepIt: "Bewaar hem"
        case .workoutDays: "Trainingsdagen"
        case .addADay: "Dag toevoegen"
        case .startAWorkout: "Start een workout"
        case .programSettings: "Programma-instellingen"
        case .unitProgressionPlateRack: "eenheid, progressie, platenrek"
        case .thatProgramIsGone: "Dat programma is weg."
        case .back: "Terug"
        case .name: "Naam"
        case .weightUnit: "Gewichtseenheid"
        case .progression: "Progressie"
        case .plateRack: "Platenrek"
        case .done: "Klaar"
        case .cancel: "Annuleer"
        case .save: "Bewaar"
        case .renameTheProgram: "Hernoem het programma"
        case .saveTheName: "Bewaar de naam"
        case .renamingChangesNothing:
            "Hernoemen verandert verder niets. Afgeronde workouts houden de naam waarmee ze gelogd zijn."
        case .progressionMode: "Progressiemodus"
        case .weightUnitDefaultNote:
            "De gewichtseenheid is alleen de standaard voor nieuwe oefeningen. De progressiemodus verplaatst elke oefening die hem niet overschrijft."
        case .nameTheDay: "Geef de dag een naam"
        case .addTheDay: "Voeg de dag toe"
        case .dayNameHint: "Push, Upper A, Legs — hoe je het in de gym noemt."
        case .giveItANameFirst: "Geef het eerst een naam."
        case .aProgramNeedsOneDay: "Een programma heeft minstens één trainingsdag."
        case .standardRack: "Standaard"
        case .customRack: "Aangepast"
        case .equipmentType: "Materiaal"
        case .newExercise: "Nieuwe oefening"
        case .saveExercise: "Bewaar"
        case .removeExercise: "Verwijder oefening"
        case .progressionForThisExercise: "Progressie voor deze oefening"
        case .discardThisExercise: "Deze oefening weggooien?"
        case .keepEditing: "Blijf bewerken"
        case .nothingSavedUntilSave: "Er is niets bewaard tot je op bewaar tikt."
        case .removeThisExercise: "Deze oefening verwijderen?"
        case .leavesProgramFromToday:
            "Hij verdwijnt vanaf vandaag uit het programma. Afgeronde workouts houden de sets die je logde."
        case .baseWeightMachine: "Basisgewicht (machine)"
        case .stackStep: "Stack step"
        case .firstPlate: "Eerste plaat"
        case .sets: "Sets"
        case .repRange: "Rep-bereik"
        case .totalWorkingWeight: "Totaal werkgewicht"
        case .increment: "Increment"
        case .microloadingIncrement: "Microloading-increment"
        case .noMicroplatesSetUpRack: "Geen microplates · zet je rek klaar"
        case .baseWeightAppears: "Basisgewicht verschijnt zodra je Machine (schijven) kiest."
        case .changesSaveOnClose: "Je wijzigingen worden bewaard als je dit blad sluit."
        case .nameYourProgram: "Geef je programma\neen naam"
        case .continueLabel: "Verder"
        case .yourPlateRack: "Jouw platenrek"
        case .thisIsMyRack: "Dit is mijn rek"
        case .platesYouOwn: "Platen die je hebt"
        case .microplates: "Microplates"
        case .stackAddOns: "Stack add-ons"
        case .switchItOff: "Zet hem uit"
        case .microplatesNeed: "Microloading heeft een microplate nodig die je hebt. Zet aan wat in je gym ligt."
        case .noPlateSwitchedOn: "Er staat geen plaat aan."
        case .withMicroloading: "met microloading"
        case .nothingOn: "niets"
        case .thisUnitApplies:
            "Deze eenheid geldt voor elke barbell, dumbbell, machine (schijven) en eigen-gewicht oefening in het programma."
        case .history: "Geschiedenis"
        case .progress: "Voortgang"
        case .summary: "Samenvatting"
        case .reweigh: "Opnieuw wegen"
        case .weight: "Gewicht"
        case .weekInARow: "Week op rij"
        case .weeksInARow: "Weken op rij"
        case .finishFirstWorkoutLandsHere: "Rond je eerste workout af en hij landt hier."
        case .finishWorkoutLandsExercisesHere:
            "Rond een workout af en elke oefening die je trainde landt hier."
        case .thatExerciseIsGone: "Die oefening is weg."
        case .oneSessionIsADot: "Eén sessie is een punt, geen klim. Train hem nog eens."
        case .thisExerciseGetsALine: "Deze oefening krijgt een lijn zodra je hem twee keer hebt getraind."
        case .wentUp: "Ging omhoog"
        case .stayed: "Bleef"
        case .oneOff: "Eenmalig"
        case .skipped: "Overgeslagen"
        case .lastSessions: "Laatste sessies"
        case .timesUp: "Keer omhoog"
        case .pinUnchanged: "Pin, onveranderd"
        case .onThePin: "Op de pin"
        case .sinceThen: "Sindsdien"
        case .workingWeight: "Werkgewicht"
        case .pin: "Pin"
        case .microloadOnThePin: "Microload op de pin"
        case .nothingWentUp: "Niets ging omhoog"
        case .exerciseWentUp: "Oefening ging omhoog"
        case .exercisesWentUp: "Oefeningen gingen omhoog"
        case .hoppaAlreadyChangedTheWeight:
            "Hoppa heeft het gewicht al aangepast. De volgende keer ligt het op de stang."
        case .noExercisesPerformed: "Geen oefeningen uitgevoerd."
        case .nextTime: "Volgende keer"
        case .duration: "Duur"
        case .volumeSuffix: "volume"
        case .removedFromTheProgram: "Verwijderd uit het programma"
        case .thatWorkoutIsGone: "Die workout is weg."
        case .everyExerciseHasAWeight: "Elke oefening heeft een gewicht."
        case .reweighIntro:
            "Een oefening zonder gewicht logt geen set en gaat niet omhoog. Typ wat je er nu mee tilt."
        case .noBaseWeight: "geen basisgewicht"
        case .noIncrement: "geen increment"
        case .noMicroplate: "geen microplate"
        case .finishWorkout: "Rond workout af"
        case .discardTheWorkout: "Gooi de workout weg"
        case .changeTheWeight: "Verander het gewicht"
        case .skipThisExercise: "Sla deze oefening over"
        case .doneEarly: "Eerder klaar"
        case .putItBack: "Zet hem terug"
        case .notAtAll: "helemaal niet"
        case .reopen: "opnieuw openen"
        case .notSetYet: "nog niet gezet"
        case .notDone: "niet gedaan"
        case .resting: "Rust"
        case .ready: "Klaar"
        case .noWeightYetTap: "Nog geen gewicht. Tik op het streepje hierboven en typ er een."
        case .setTheWeight: "Zet het gewicht"
        case .justToday: "Alleen vandaag"
        case .fromNowOn: "Vanaf nu"
        case .justTodayOrFromNowOn: "Alleen vandaag, of vanaf nu?"
        case .thatDayIsGone: "Die dag is weg."
        case .hoppaCouldNotRead: "Hoppa kon het logboek niet lezen."
        case .nothingChangedOnPhone:
            "Er is niets veranderd en niets weggeschreven. Het bestand staat nog op de telefoon."
        case .removedFromProgramKept: "Hij is uit het programma gehaald. Wat je logde blijft bewaard."
        case .dayDone: "Dag klaar"
        case .removeDay: "Verwijder dag"
        case .rename: "Hernoem"
        case .addAnExercise: "Voeg een oefening toe"
        case .noExercisesYet: "Nog geen oefeningen"
        case .renameTheDay: "Hernoem de dag"
        case .removeThisDay: "Deze dag verwijderen?"
        case .chartPin: "Pin"
        case .chartWorkingWeight: "Werkgewicht"
        case .mixedUnitNothingConverts: "Hier wordt niets omgerekend."
        case .setAtLabel: "Set op"
        case .perSide: "Per kant"
        case .closest: "≈ dichtstbij"
        case .useNameAsTyped: "Gebruik deze naam zoals je hem typte"
        case .discard: "Weggooien"
        case .youCanRenameItLater: "Je kunt hem later hernoemen."
        case .whatHoppaAlreadyPicked: "Wat Hoppa al koos"
        case .hoppaPickedTheseThree:
            "Hoppa koos deze drie voor je. Tik er alleen op als het mis is."
        case .keepLogging: "Blijf loggen"
        case .skipAndFinish: "Sla over en rond af"
        case .finishTheWorkout: "Rond de workout af"
        case .deleteThisWorkout: "Deze workout verwijderen?"
        case .deleteWorkout: "Verwijder workout"
        case .workingWeightsStay: "Je werkgewichten blijven waar ze zijn."
        case .eachHand: "per hand"
        case .addedWeightOnly: "alleen extra gewicht"
        case .noPlates: "geen platen"
        case .noSetsYet: "Nog geen sets"
        case .leavingOpenExercise:
            "Een open oefening verlaten is later, nooit \"helemaal niet\"."
        case .hoppaKeepsOneWorkout:
            "Hoppa houdt één workout open. Rond die eerst af of gooi hem weg."
        case .close: "Sluit ✕"
        case .reps: "Reps"
        case .tapARowToOpenIt: "tik een rij om hem te openen"
        case .dayLeavesKeepName:
            "Hij verdwijnt vanaf vandaag uit het programma. Afgeronde workouts houden hun naam en de sets die je logde."
        case .everyExerciseEndsCompleted: "Elke oefening eindigt nog steeds als gedaan of overgeslagen."
        case .oneOffNeverWritten: "een eenmalig gewicht · nooit teruggeschreven"
        case .becomesWorkingWeight: "dit wordt het werkgewicht"
        case .skipIt: "Sla hem over"
        case .skipThem: "Sla ze over"
        case .notBuiltYet: "Nog niet gebouwd"
        case .remove: "Verwijder"
        case .delete: "Verwijder"
        case .stranded: "gestrand"
        case .micro: "Micro"
        case .completed: "gedaan"
        case .openLabel: "open"
        case .now: "Nu"
        case .next: "Volgende"
        case .onTheBelt: "aan de riem"
        case .over: "te zwaar"
        case .under: "te licht"
        case .unitSwitchClears:
            "Elke barbell, dumbbell, machine (schijven) en eigen-gewicht oefening verliest zijn gewicht, increment en basisgewicht, en elk microloading-increment wordt gereset. Het volgende scherm vraagt de gewichten opnieuw."
        case .stateOpen: "Open"
        case .stateCompleted: "Gedaan"
        case .willNotProgress: "gaat niet omhoog"
        case .ticket: "Ticket"
        case .plateNoun: "plaat"
        }
    }
}
