extension Phrasebook {
    func english(_ phrase: Phrase) -> String {
        switch phrase {
        case .tabHome: "Home"
        case .tabHistory: "History"
        case .tabProgress: "Progress"
        case .tabSettings: "Settings"
        case .language: "Language"
        case .selected: "Selected"
        case .nothingHereYet: "Nothing here yet"
        case .createAProgram: "Create a program"
        case .pickADay: "Pick a day"
        case .running: "Running"
        case .hoppaCannotReadLogbook: "Hoppa cannot read your logbook."
        case .fileUnchanged: "Nothing was changed. The file is exactly as it was."
        case .resume: "Resume"
        case .finishIt: "Finish it"
        case .discardIt: "Discard it"
        case .discardThisWorkout: "Discard this workout?"
        case .everyLoggedSetGoes: "Every logged set goes. Hoppa keeps nothing."
        case .keepIt: "Keep it"
        case .workoutDays: "Workout days"
        case .addADay: "Add a day"
        case .startAWorkout: "Start a workout"
        case .programSettings: "Program settings"
        case .unitProgressionPlateRack: "unit, progression, plate rack"
        case .thatProgramIsGone: "That program is gone."
        case .back: "Back"
        case .name: "Name"
        case .weightUnit: "Weight unit"
        case .progression: "Progression"
        case .plateRack: "Plate rack"
        case .done: "Done"
        case .cancel: "Cancel"
        case .save: "Save"
        case .renameTheProgram: "Rename the program"
        case .saveTheName: "Save the name"
        case .renamingChangesNothing:
            "Renaming changes nothing else. Finished workouts keep the name they were logged with."
        case .progressionMode: "Progression mode"
        case .weightUnitDefaultNote:
            "The weight unit is the default for new exercises only. Changing the progression mode moves every exercise that does not override it."
        case .nameTheDay: "Name the day"
        case .addTheDay: "Add the day"
        case .dayNameHint: "Push, Upper A, Legs — whatever you call it in the gym."
        case .giveItANameFirst: "Give it a name first."
        case .aProgramNeedsOneDay: "A program needs at least one workout day."
        case .standardRack: "Standard"
        case .customRack: "Custom"
        case .equipmentType: "Equipment type"
        case .newExercise: "New exercise"
        case .saveExercise: "Save"
        case .removeExercise: "Remove exercise"
        case .progressionForThisExercise: "Progression for this exercise"
        case .discardThisExercise: "Discard this exercise?"
        case .keepEditing: "Keep editing"
        case .nothingSavedUntilSave: "Nothing is saved until you tap save."
        case .removeThisExercise: "Remove this exercise?"
        case .leavesProgramFromToday:
            "It leaves the program from today. Finished workouts keep the sets you logged."
        case .baseWeightMachine: "Base weight (machine)"
        case .stackStep: "Stack step"
        case .firstPlate: "First plate"
        case .sets: "Sets"
        case .repRange: "Rep range"
        case .totalWorkingWeight: "Total working weight"
        case .increment: "Increment"
        case .microloadingIncrement: "Microloading increment"
        case .noMicroplatesSetUpRack: "No microplates · set up your rack"
        case .baseWeightAppears: "Base weight appears as soon as you pick Machine (Plates)."
        case .changesSaveOnClose: "Your changes save when you close this sheet."
        case .nameYourProgram: "Name your\nprogram"
        case .continueLabel: "Continue"
        case .yourPlateRack: "Your plate rack"
        case .thisIsMyRack: "This is my rack"
        case .platesYouOwn: "Plates you own"
        case .microplates: "Microplates"
        case .stackAddOns: "Stack add-ons"
        case .switchItOff: "Switch it off"
        case .microplatesNeed: "Microloading needs a microplate you own. Switch on what is in your gym."
        case .noPlateSwitchedOn: "No plate is switched on."
        case .withMicroloading: "with microloading"
        case .nothingOn: "nothing"
        case .thisUnitApplies:
            "This unit applies to every barbell, dumbbell, machine (plates) and bodyweight exercise in the program."
        case .history: "History"
        case .progress: "Progress"
        case .summary: "Summary"
        case .reweigh: "Re-weigh"
        case .weight: "Weight"
        case .weekInARow: "Week in a row"
        case .weeksInARow: "Weeks in a row"
        case .finishFirstWorkoutLandsHere: "Finish your first workout and it lands here."
        case .finishWorkoutLandsExercisesHere:
            "Finish a workout and every exercise you trained lands here."
        case .thatExerciseIsGone: "That exercise is gone."
        case .oneSessionIsADot: "One session is a dot, not a climb. Train it once more."
        case .thisExerciseGetsALine: "This exercise gets a line once you have trained it twice."
        case .wentUp: "Went up"
        case .stayed: "Stayed"
        case .oneOff: "One-off"
        case .skipped: "Skipped"
        case .lastSessions: "Last sessions"
        case .timesUp: "Times up"
        case .pinUnchanged: "Pin, unchanged"
        case .onThePin: "On the pin"
        case .sinceThen: "Since then"
        case .workingWeight: "Working weight"
        case .pin: "Pin"
        case .microloadOnThePin: "Microload on the pin"
        case .nothingWentUp: "Nothing went up"
        case .exerciseWentUp: "Exercise went up"
        case .exercisesWentUp: "Exercises went up"
        case .hoppaAlreadyChangedTheWeight:
            "Hoppa already changed the weight. Next time it is on the bar."
        case .noExercisesPerformed: "No exercises performed."
        case .nextTime: "Next time"
        case .duration: "Duration"
        case .volumeSuffix: "volume"
        case .removedFromTheProgram: "Removed from the program"
        case .thatWorkoutIsGone: "That workout is gone."
        case .everyExerciseHasAWeight: "Every exercise has a weight."
        case .reweighIntro:
            "An exercise with no weight logs no set and does not progress. Type what you lift it with now."
        case .noBaseWeight: "no base weight"
        case .noIncrement: "no increment"
        case .noMicroplate: "no microplate"
        case .finishWorkout: "Finish workout"
        case .discardTheWorkout: "Discard the workout"
        case .changeTheWeight: "Change the weight"
        case .skipThisExercise: "Skip this exercise"
        case .doneEarly: "Done early"
        case .putItBack: "Put it back"
        case .notAtAll: "not at all"
        case .reopen: "reopen"
        case .notSetYet: "not set yet"
        case .notDone: "not done"
        case .resting: "Resting"
        case .ready: "Ready"
        case .noWeightYetTap: "No weight yet. Tap the dash above and type one."
        case .setTheWeight: "Set the weight"
        case .justToday: "Just today"
        case .fromNowOn: "From now on"
        case .justTodayOrFromNowOn: "Just today, or from now on?"
        case .thatDayIsGone: "That day is gone."
        case .hoppaCouldNotRead: "Hoppa could not read the logbook."
        case .nothingChangedOnPhone:
            "Nothing was changed and nothing was written. The file is still on the phone."
        case .removedFromProgramKept: "It was removed from the program. What you logged is kept."
        case .dayDone: "Day done"
        case .removeDay: "Remove day"
        case .rename: "Rename"
        case .addAnExercise: "Add an exercise"
        case .noExercisesYet: "No exercises yet"
        case .renameTheDay: "Rename the day"
        case .removeThisDay: "Remove this day?"
        case .chartPin: "Pin"
        case .chartWorkingWeight: "Working weight"
        case .mixedUnitNothingConverts: "Nothing here converts."
        case .setAtLabel: "Set at"
        case .perSide: "Per side"
        case .closest: "≈ closest"
        case .useNameAsTyped: "Use this name as you typed it"
        case .discard: "Discard"
        case .youCanRenameItLater: "You can rename it later."
        case .whatHoppaAlreadyPicked: "What Hoppa already picked"
        case .hoppaPickedTheseThree:
            "Hoppa picked these three for you. Tap one only if it is wrong."
        case .keepLogging: "Keep logging"
        case .skipAndFinish: "Skip and finish"
        case .finishTheWorkout: "Finish the workout"
        case .deleteThisWorkout: "Delete this workout?"
        case .deleteWorkout: "Delete workout"
        case .workingWeightsStay: "Your working weights stay where they are."
        case .eachHand: "each hand"
        case .addedWeightOnly: "added weight only"
        case .noPlates: "no plates"
        case .noSetsYet: "No sets yet"
        case .leavingOpenExercise:
            "Leaving an open exercise means later, never \"not at all\"."
        case .hoppaKeepsOneWorkout:
            "Hoppa keeps one workout open at a time. Finish or discard that one first."
        case .close: "Close ✕"
        case .reps: "Reps"
        case .tapARowToOpenIt: "tap a row to open it"
        case .dayLeavesKeepName:
            "It leaves the program from today. Finished workouts keep their name and the sets you logged."
        case .everyExerciseEndsCompleted: "Every exercise still ends completed or skipped."
        case .oneOffNeverWritten: "a one-off weight · never written back"
        case .becomesWorkingWeight: "this becomes the working weight"
        case .skipIt: "Skip it"
        case .skipThem: "Skip them"
        case .notBuiltYet: "Not built yet"
        case .remove: "Remove"
        case .delete: "Delete"
        case .stranded: "stranded"
        case .micro: "Micro"
        case .completed: "completed"
        case .openLabel: "open"
        case .now: "Now"
        case .next: "Next"
        case .onTheBelt: "on the belt"
        case .over: "over"
        case .under: "under"
        case .unitSwitchClears:
            "Every barbell, dumbbell, machine (plates) and bodyweight exercise loses its weight, its increment and its base weight, and every microloading increment resets. The next screen asks for the weights again."
        case .stateOpen: "Open"
        case .stateCompleted: "Completed"
        case .willNotProgress: "will not progress"
        case .ticket: "Ticket"
        case .plateNoun: "plate"
        }
    }
}
